name: Javascript

on:
  push:
    paths:
      - "**.js"
      - ".github/**"
  pull_request:
    paths:
      - "**.js"
      - ".github/**"

jobs:
  xo:
    name: check js with xo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run xo
        run: ./node_modules/.bin/xo
