name: Main

on: [push, pull_request]

jobs:
  prettier:
    name: check files with prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run prettier
        uses: actionsx/prettier@v2
        with:
          args: --check .
